# spring.application.name=vote
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=e-sun;encrypt=true;trustServerCertificate=true
spring.datasource.username=e-sun
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver